### ISSUE TITLE
How to remove bedrock (or prevent a chunk generation)?

### ISSUE THREAD

**Issue by MichaelHilus** [rutgerkok/WorldGeneratorApi#12]
I would like to have my world end after 1000 blocks from center (`x = 0` and `z = 0`).

Using a `BaseTerrainGenerator`, I could already make the chunks generate vanilla like within the circular world border and contain (nearly!) only air when they are outside the border.

But actually, all my chunks outside the border still have the bottom bedrock layers. I thought that with

    chunk.getBlocksForChunk().setRegion(0, 0, 0, CHUNK_SIZE, 255, CHUNK_SIZE, Material.AIR);

I could have totally empty chunks, but I must have missed someting. Is there a possibility to remove or override the bedrock layers? Or even to not have these chunks outside the border be generated?

**Comment by rutgerkok** [comment]
Bedrock is generated after the initial stone has been generated. Unlike most other things, it can generate in air. To disable bedrock, use:

`worldGenerator.getWorldDecorator().withoutDefaultBaseDecorations(BaseDecorationType.BEDROCK);`

You then need to generate bedrock yourself:

`worldGenerator.getWorldDecorator().withCustomBaseDecoration(BaseDecorationType.BEDROCK, myBedrockGenerator);`

[Here's how vanilla does it.](https://github.com/rutgerkok/WorldGeneratorApi/blob/c5cbca9c9bdc76556dc42b5f7c0442c3f9956c00/worldgeneratorapi-impl/src/main/java/nl/rutgerkok/worldgeneratorapi/internal/bukkitoverrides/InjectedChunkGenerator.java#L200)

**Comment by MichaelHilus** [comment]
Thanks a lot, that works perfectly.
