### ISSUE TITLE
InjectedBiomeGenerator Exception

### ISSUE THREAD

**Issue by RomainStorai** [rutgerkok/WorldGeneratorApi#15]
**Describe the bug**
While generating a world with a custom biome generator, I got this error (I was generating chunk 967 / 2601)

Version: latest build, Paper 92, Java 8

`java.lang.ClassCastException: nl.rutgerkok.worldgeneratorapi.internal.InjectedBiomeGenerator cannot be cast to net.minecraft.server.v1_16_R1.WorldChunkManagerHell`

**Log files**
https://hastebin.com/emagocoduq.bash

**Comment by rutgerkok** [comment]
See #14 .
