### ISSUE TITLE
How to generate a plains with desert surface?

### ISSUE THREAD

**Issue by skp81** [rutgerkok/WorldGeneratorApi#21]
I don't know if the api can do this.

**Comment by skp81** [comment]
I mean replace vanilla plains surface to desert surface, but structure, terrain etc not change.

**Comment by rutgerkok** [comment]
If you just want to replace the dirt and grass with sand, that can be done as follows:

```java
private class SandGenerator implements BaseChunkGenerator {

            private final int seaLevel;

            private BeachGenerator(int seaLevel) {
                this.seaLevel = seaLevel;
            }

            @Override
            public void setBlocksInChunk(GeneratingChunk chunk) {
                for (int x = 0; x < CHUNK_SIZE; x++) {
                    for (int z = 0; z < CHUNK_SIZE; z++) {
                        Biome biome = chunk.getBiomesForChunk().getBiome(x, 70, z);
                        if (biome != Biome.PLAINS) {
                            return;
                        }
                        for (int y = 61; y < 128; y++) {
                            Material old = chunk.getBlocksForChunk().getType(x, y, z);
                            if (old == Material.DIRT || old == Material.GRASS_BLOCK) {
                                chunk.getBlocksForChunk().setBlock(x, y, z, Material.SAND);
                            }
                        }
                    }
                }
            }
    }
```

It's a bit of a hack, but there's no dedicated API to change biome settings. An alternative way to change the vanilla biomes is through the [Custom world type](https://minecraft.gamepedia.com/Custom).

**Comment by dadusakyt** [comment]
Does this still work? Because when I used this code (with some minor changed because it seems like some stuff was deprecated) it just created an empty world - no blocks, just structures.

**Comment by rutgerkok** [comment]
Yes, but you need to add this class as a decorator (`generator.getWorldDecorator().withCustomBaseDecoration(...)`), instead of using it as the base chunk generator.

A decorator is used to decorate existing terrain, in this case to replace dirt and grass with sand. A base chunk generator is used to generate the initial shape of the terrain, which the above code doesn't do, so you end up with an empty world.
