### ISSUE TITLE
Download on Spigot org is missing plugin.yml

### ISSUE THREAD

**Issue by RingOfStorms** [rutgerkok/WorldGeneratorApi#23]
**Describe the bug**
When downloading jar from https://www.spigotmc.org/resources/worldgeneratorapi.77976/ it is missing a plugin yml
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/2099212/98507840-0308af80-2224-11eb-9b84-8f15fe806521.png">

** Workaround ** The jar from github releases is fine.

**Comment by rutgerkok** [comment]
I previously uploaded the API jar to SpigotMC, and then tried to fix it by reuploading. However, it seems SpigotMC.org does not accept new files unless I change the version number too. The website says "If you do not enter this, a new version will not be posted.", but apparantly the same goes if you do not increment the version number.

Did a workaround: I replaced the dots in the version number with [this char](http://www.amp-what.com/unicode/search/dot) on SpigotMC.org, and now it accepts my new file.

Thanks for reporting!
