### ISSUE TITLE
FYI: new game using your API

### ISSUE THREAD

**Issue by tastybento** [rutgerkok/WorldGeneratorApi#32]
I'm not sure how to contact you so I just thought I'd let you know that I released a new game that uses your API. It's called "Boxed" https://github.com/BentoBoxWorld/Boxed. Here's a video I made: https://youtu.be/e0bzc_kGwC0. Thanks for your hard work!

**Comment by rutgerkok** [comment]
Nice work! I added it to the plugin list at https://www.spigotmc.org/resources/worldgeneratorapi.77976/ .
