### ISSUE TITLE
Bastion generation?

### ISSUE THREAD

**Issue by tastybento** [rutgerkok/WorldGeneratorApi#34]
Thanks for the help on the nether generation. I now have a functional nether with various biomes. 

Is there any reason why Bastions would not be pasted?  I can move to the location where one should be because I obtain the advancement "Those were the days", but there is nothing actually at that location. I used spectator mode to check if it was embedded in the nether rack above and below but nothing. I assume it has been logged as being in that location but the structure was not actually pasted for some reason. Nether fortresses appear correctly, just not Bastions. The screenshot is after I just received the advancement:

<img width="1680" alt="Screen Shot 2021-03-24 at 9 28 03 PM" src="https://user-images.githubusercontent.com/4407265/112419205-39812b80-8ce8-11eb-934b-31680c7d3602.png">

**Comment by rutgerkok** [comment]
Strange, for me it's generating perfectly fine. Maybe the spawning conditions were unfavourable for that location?

![afbeelding](https://user-images.githubusercontent.com/1462188/112759695-7739c900-8ff4-11eb-84e4-db12e8b4f10d.png)

**Comment by tastybento** [comment]
Ugh. Okay, thanks for checking. Now I wonder what the spawning conditions are...

**Comment by tastybento** [comment]
What settings did you use for that world? Sea level, land height? I'm trying super flats now but still see the same issue.

**Comment by rutgerkok** [comment]
I'm just using [Pancake v1.0 (default settings)](https://github.com/rutgerkok/PancakeWorldGenerator/releases/tag/v1.0) as the terrain generator for the Nether world. Maybe it's a biome issue? Pancake doesn't change the biome layout.

Structure locations are stored in `world_nether/DIM-1/poi`. Did you delete that folder too when you reset the world? Maybe that file got outdated.

**Comment by tastybento** [comment]
I found the problem, a bug on my side. I had `generator.getWorldDecorator().withoutDefaultDecorations(DecorationType.SURFACE_STRUCTURES);` active in the nether, which weirdly doesn't affect fortresses, but does affect Bastions!
