### ISSUE TITLE
Not Overriding the #getHeight method in BaseTerrainGenerator will throw an RunTimeException

### ISSUE THREAD

**Issue by apollyon600** [rutgerkok/WorldGeneratorApi#39]
Title says it all, when not overriding the new #getHeight method, it automatically runs the old getHeight method and then throws an exception, meaning you're required to override a return int in #getHeight

**Comment by rutgerkok** [comment]
Indeed, you need to override `int getHeight(BiomeGenerator biomeGenerator, int x, int z, HeightType type)`. This is working as intended. It's used by villages and a few other structures to probe the height map.

You can use a noise generator instead if you're looking for an easier way to implement hilly terrain - https://github.com/rutgerkok/WorldGeneratorApi/wiki/Creating-hilly-terrain .
