### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R1/BiomeBase

### ISSUE THREAD

**Issue by DuendeInexistente** [rutgerkok/WorldGeneratorApi#4]
**Describe the bug**
The plugin crashes during the server load, without crashing spigot itself.

**To Reproduce**
1. Built spigot
2. Ran it with worldgenerator's latest release (I tried to build it myself, but it gave me an error which seems to be related), and received the error linked below.

**Log files**
Release error (Spigot): https://pastebin.com/hKamkjhb
Build error: https://pastebin.com/RENnSfmV

**Comment by rutgerkok** [comment]
Yeah, Spigot changed the obfuscation of the net.minecraft.server code. I will fix this.
