### ISSUE TITLE
Minecraft 1.17 compatibility

### ISSUE THREAD

**Issue by ErythroCraft** [rutgerkok/WorldGeneratorApi#42]
Hi.

Your plugin will not loading on 1.17 test server

server:
CraftBukkit version dev-Spigot-66f9d3c-cbf2f67 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

Console line:
[19:10:41] [Server thread/ERROR]: Could not load 'plugins\WorldGeneratorApi.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_16_R3/CraftServer

Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_16_R3/CraftServer

Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_16_R3.CraftServer

**Comment by rutgerkok** [comment]
Yes, it will need to be updated. I'll update another plugin (BetterEnderChest) first, as that plugin is less complex. It also allows me to learn how 1.17 is structured, as Mojang and Spigot made quite some changes to the code. Then the update to WorldGeneratorApi will start.

**Comment by rutgerkok** [comment]
Still ongoing - a few more classes to rewrite for Minecraft 1.17 and then the testing can actually start.

**Comment by rutgerkok** [comment]
Fixed in version 1.2.0.
