### ISSUE TITLE
[Questions] 1.15 and more?

### ISSUE THREAD

**Issue by Fundryi** [rutgerkok/WorldGeneratorApi#5]
Hi, cool API/plugin you have here.

I just have some small questions if it's okay.

Will you update this to 1.15 and Upcoming updates?
If I would use this, Would I have to "recreate" configs for every Biom again or is this more just a tool to edit the default ones?
Is it possible to disable Ocean/River/some biomes completely?

My Situation right now is, that I use TerrainControll and no other Worldgen is supporting 1.14(with good/custom settings), and what I would need is, completely disabled Oceans/Rivers/Some Biomes and make the size of the rest Smaller so they are more compact spawned.
I used this for a minigame, which I would really like to update to 1.14 xD

I'm not the dev who will code this, I'm just curios upfront if this stuff is possible with your API before I get the dev that will work on this, invested time into reading/understanding your API.

Hope you understand.

Regards!

**Comment by rutgerkok** [comment]
It's already updated to 1.15, I just haven't uploaded a JAR file yet.

Right now, you can edit the terrain shape and the decorations (caves, trees, etc.), but editing the biome locations or adding custom biomes is not possible. So changing the size of biomes or disabling some is not possible.

Maybe you can use an older Minecraft version, back from when TerrainControl was still available, and then upgrade the world?

**Comment by Fundryi** [comment]
ahh sad life ;( 
Most important stuff would be just to disable Ocean xD

We thought about that with the worldgen on older version and than copy it, but we would like to use every feauter of 1.14/1.15 :/ and it would also need just a server for worldgen.

Just sad that no one is updating TerrainControll anymore even tho its under MIT Licens...

Thanks for the answer tho... :)

**Comment by rutgerkok** [comment]
The plugin is just so big that it's very difficult to maintain, especially with Minecraft internals changing so much with every release.

If your minigame doesn't require truly random worlds, then maybe you can find 10 seeds that have no ocean close to the spawn? If you combine that with a random spawn location somewhere from -1000 to 1000 blocks from the original spawn, then it could maybe work well enough.

**Comment by Fundryi** [comment]
Welp IF Mojang wouldn't have removed the Customize Option in SP/Generation-Settings in 1.13 everything would be fine xD
YOu could adjust nearly everything in there, but now if u try to use it with 1.14 it just doesn't work. 
Just a bad move from them yikes :P

Welp looks like I'm kinda stuck at 1.8 for the time being, let's just hope Hytale does it better ;)
