### ISSUE TITLE
Plugin Won't Load On Paper 1.19

### ISSUE THREAD

**Issue by Joshua444454** [rutgerkok/WorldGeneratorApi#56]
I install the plugin and start the server I get this error in the console "Could not load 'plugins/WorldGeneratorApi.jar' in folder 'plugins'"

1. Install The Plugin
2. Start The Server
3. See error

**Comment by rutgerkok** [comment]
Thanks for reporting, but I'm not going to fix this myself. I used this plugin when 1.19 was brand new to generate some biome maps, which was all I needed for my server. So I don't really want to make further updates right now.
