### ISSUE TITLE
Noise generator implementation

### ISSUE THREAD

**Issue by 19lmyers** [rutgerkok/WorldGeneratorApi#8]
I've been playing around with the Noise Generator exposed by the API, but I've gotten a bit confused. I read [here](https://gamedev.stackexchange.com/questions/12603/how-is-a-3d-perlin-noise-function-used-to-generate-terrain) that Minecraft uses noise as "density," which was reflected in my tests.

But I'm still not sure what I should be doing with the 33 buffer values to achieve vanilla-like terrain.

**Comment by rutgerkok** [comment]
As a start, you could take the output of a 3D noise function. [Bukkit includes a few](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/util/noise). Every value in the buffer represents 8 blocks in height and 4x4 blocks on the x and z axis. This will give you some liquid-like terrain. Then, to make sure you have stone at the bottom and air at the top, add some value to the lower indexes and subtract some value from the higher indexes.

If you want *exact* vanilla terrain, you can use [Dough](https://github.com/rutgerkok/Dough), which is just the Minecraft 1.12 terrain generator with all the settings from the Customized world type still present.

**Comment by 19lmyers** [comment]
My goal is to implement custom terrain, I just am having a hard time understanding how vanilla-like terrain is generated. For example, using Bukkit's built-in Simplex noise generator the closest I can get (with some biome-specific tweaks) is this:
![image](https://user-images.githubusercontent.com/14363487/80047794-3cb1dd00-84c3-11ea-8ac9-3b1e040ee66d.png)

**Comment by 19lmyers** [comment]
Thank you so much, I get it now!

**Comment by rutgerkok** [comment]
Great to hear that!
