### ISSUE TITLE
World always fills Y<63 with water

### ISSUE THREAD

**Issue by 19lmyers** [rutgerkok/WorldGeneratorApi#9]
I couldn't find the decorator / terrain class responsible for this. How do I change it / turn it off?
I've been able to change the surface height successfully.

**Comment by rutgerkok** [comment]
You can override [this method](https://github.com/rutgerkok/WorldGeneratorApi/blob/86cf62e75b8a943e7d819f5dcfff9f84e3f13673/worldgeneratorapi/src/main/java/nl/rutgerkok/worldgeneratorapi/BaseNoiseGenerator.java#L78) in your BaseNoiseGenerator implementation.

**Comment by 19lmyers** [comment]
Thanks!
